name: Build and Publish Front End Image to DockerHub. Then Update EKS Deployment
on: 
    [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build image
        run: docker build ./frontend -t ${{ secrets.DOCKERHUB_USERNAME }}/devops-fileconverter-frontend:latest
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push image to docker hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/devops-fileconverter-frontend:latest
          echo "Image pushed to Docker Hub"
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Update EKS Deployment
        run: |
          kubectl rollout restart deployment/frontend
          echo "Deployment rollout restarted"